# Generated by Django 4.2.20 on 2025-05-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicflo_api', '0003_update_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_telegram_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_telegram_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_telegram_admin'], name='unicflo_api_is_tele_dbbef9_idx'),
        ),
    ]
