# Generated by Django 4.2.20 on 2025-05-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicflo_api', '0004_user_is_telegram_admin_user_is_telegram_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subcategory',
            name='unicflo_api_categor_dc12d7_idx',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['is_active'], name='unicflo_api_is_acti_c1c44b_idx'),
        ),
    ]
