# Generated by Django 4.2.20 on 2025-05-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicflo_api', '0005_remove_subcategory_unicflo_api_categor_dc12d7_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Customer's phone number for order communication", max_length=20),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['created_at'], name='unicflo_api_created_749338_idx'),
        ),
    ]
