# Generated by Django 4.2.20 on 2025-05-22 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicflo_api', '0007_add_session_key_to_cart_and_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_shipping', 'Free Shipping'), ('buy_one_get_one', 'Buy One Get One')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('is_first_purchase_only', models.BooleanField(default=False)),
                ('is_new_user_only', models.BooleanField(default=False)),
                ('is_birthday_only', models.BooleanField(default=False)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('seasonal_start_month', models.PositiveIntegerField(blank=True, null=True)),
                ('seasonal_end_month', models.PositiveIntegerField(blank=True, null=True)),
                ('min_items_in_cart', models.PositiveIntegerField(default=1)),
                ('max_items_in_cart', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-last_used'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ['price', 'min_days'], 'verbose_name': 'Shipping Method', 'verbose_name_plural': 'Shipping Methods'},
        ),
        migrations.AddField(
            model_name='address',
            name='address_label',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='delivery_instructions',
            field=models.TextField(blank=True, help_text='Special instructions for delivery'),
        ),
        migrations.AddField(
            model_name='address',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark for easier delivery', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Special delivery instructions'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_wrapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('cash_on_delivery', 'Cash on Delivery')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_delivery_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='save_billing_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='save_shipping_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='available_time_slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='delivery_type',
            field=models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery'), ('same_day', 'Same Day Delivery'), ('scheduled', 'Scheduled Delivery')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='free_shipping_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='insurance_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='insurance_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='tracking_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address_label'], name='unicflo_api_address_4ecfef_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['last_used'], name='unicflo_api_last_us_38ba44_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['usage_count'], name='unicflo_api_usage_c_bcca00_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method'], name='unicflo_api_payment_7b2e53_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['estimated_delivery_date'], name='unicflo_api_estimat_c51a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['delivery_type'], name='unicflo_api_deliver_6f1d46_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['is_active'], name='unicflo_api_is_acti_8eadd6_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['price'], name='unicflo_api_price_db1063_idx'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, to='unicflo_api.category'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, to='unicflo_api.product'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='excluded_products',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_promos', to='unicflo_api.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='unicflo_api.promocode'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='unicflo_api_code_f760ab_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['status'], name='unicflo_api_status_88f7da_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['start_date'], name='unicflo_api_start_d_1c7867_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['end_date'], name='unicflo_api_end_dat_8074ae_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['discount_type'], name='unicflo_api_discoun_89ec1b_idx'),
        ),
    ]
