# Generated by Django 4.2.20 on 2025-05-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicflo_api', '0010_cartitem_variant_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the wishlist'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for the wishlist', max_length=100),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['created_at'], name='unicflo_api_created_bc270f_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['updated_at'], name='unicflo_api_updated_debc92_idx'),
        ),
    ]
