# Generated by Django 4.2.20 on 2025-05-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicflo_api', '0011_wishlist_description_wishlist_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['is_deleted'], name='unicflo_api_is_dele_de5694_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['deleted_at'], name='unicflo_api_deleted_9b21d2_idx'),
        ),
    ]
