# Generated by Django 4.2.20 on 2025-05-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicflo_api', '0013_remove_order_unicflo_api_estimat_c51a0f_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['city', 'name'], 'verbose_name': 'Branch Address', 'verbose_name_plural': 'Branch Addresses'},
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='unicflo_api_user_id_bbd1b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='unicflo_api_address_dfde8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='unicflo_api_is_defa_05c2e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='unicflo_api_address_4ecfef_idx',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='unicflo_api_last_us_38ba44_idx',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='unicflo_api_usage_c_bcca00_idx',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='full_name',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='is_default',
            new_name='has_fitting_room',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='is_verified',
            new_name='has_parking',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='apartment',
            new_name='manager_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_label',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='delivery_instructions',
        ),
        migrations.RemoveField(
            model_name='address',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='verification_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='address',
            name='branch_type',
            field=models.CharField(choices=[('store', 'Store'), ('pickup', 'Pickup Point'), ('warehouse', 'Warehouse')], default='store', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='is_24_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='address',
            name='location_link',
            field=models.URLField(blank=True, help_text='Google Maps link'),
        ),
        migrations.AddField(
            model_name='address',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='working_hours',
            field=models.CharField(default=1, help_text='Example: 09:00-18:00', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(help_text='Select a branch for pickup or delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='unicflo_api.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Uzbekistan', max_length=100),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='unicflo_api_city_73e94d_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['branch_type'], name='unicflo_api_branch__d4ab7b_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_active'], name='unicflo_api_is_acti_663161_idx'),
        ),
    ]
