# Generated by Django 4.2.20 on 2025-05-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicflo_api', '0014_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='branch',
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicflo_api.shippingmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(help_text='Address for home delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='unicflo_api.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_branch',
            field=models.ForeignKey(help_text='Branch for pickup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_orders', to='unicflo_api.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('cash_on_delivery', 'Cash on Delivery'), ('cash_on_pickup', 'Cash on Pickup'), ('split', 'Split Payment')], default='cash_on_delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready_for_pickup', 'Ready for Pickup'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='second_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready_for_pickup', 'Ready for Pickup'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready_for_pickup', 'Ready for Pickup'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='delivery_type',
            field=models.CharField(choices=[('branch_pickup', 'Branch Pickup'), ('home_delivery', 'Home Delivery')], default='branch_pickup', max_length=20),
        ),
    ]
