# Generated by Django 4.2.20 on 2025-05-25 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicflo_api', '0016_remove_cart_shipping_method_productrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicflo_api.promocode'),
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_code_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
