# Generated by Django 4.2.20 on 2025-05-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicflo_api', '0017_cart_promo_code_cart_promo_code_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('branch_pickup', 'Branch Pickup'), ('home_delivery', 'Home Delivery')], default='branch_pickup', max_length=20),
        ),
    ]
